### ISSUE TITLE
force_insert validation requires bool

### ISSUE THREAD

**Issue by azaroth42** [ad-freiburg/qlever-ui#91]
## Task
Trying to change the backend autocomplete defaults from 3. context sensitive to 2. context insensitive results in the following exception.

Update: Actually even trying to resubmit any change has the same issue.

## Exception Generated

```
Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/env/lib/python3.10/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/env/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1257, in save_model
    obj.save()
  File "/app/backend/models.py", line 466, in save
    super(BackendDefaults, self).save(*args, kwargs)
  File "/app/backend/models.py", line 341, in save
    super(Backend, self).save(*args, **kwargs)
  File "/env/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/env/lib/python3.10/site-packages/django/db/models/base.py", line 897, in save_base
    force_insert = self._validate_force_insert(force_insert)
  File "/env/lib/python3.10/site-packages/django/db/models/base.py", line 842, in _validate_force_insert
    raise TypeError("force_insert must be a bool or tuple.")

Exception Type: TypeError at /admin/backend/backenddefaults/36/change/
Exception Value: force_insert must be a bool or tuple.
```

## Environment

From the UI: `Git commit 27a4c98 on master`
Started via qlever ui

**Comment by hannahbast** [comment]
@azaroth42 I am seeing this only now, sorry. Can you tell me what exactly you did. In particular, did you change this in the web interface (after clicking on "Edit this backend") or did you change this somewhere in the code? And did the error message appear in the browser or on the command line?
